### ISSUE TITLE
Wix MSI package build fails with 'MSB6003: Access is denied' error message

### ISSUE THREAD

**Issue by ideook** [firegiant/HeatWaveSupport#26]
### HeatWave Version

0.9.6.1

### Visual Studio Version

17.5.2

### Repro Steps

1. Open Visual Studio.
2. Create a new WPF project.
3. Add a new "MSI Package (WIX v4)" project to the solution.
4. Add a reference to the WPF project in the WIX project.
5. Replace the Component/File Source in the ExampleComponents.wxs file with "WpfApp18.exe".
6. Build the solution.
7. The error message described above will be displayed.
I hope that helps!

### Actual Result

Severity Code Description Project File Line Suppression State
Error MSB6003 The specified task executable "wix.exe" could not be run. System.ComponentModel.Win32Exception (0x80004005): Access is denied.
at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
at Microsoft.Build.Utilities.ToolTask.Execute() Package4 C:\Users\DukhyunLee.nuget\packages\wixtoolset.sdk\4.0.0-rc.4\tools\wix.targets 585

**Comment by ideook** [comment]
It was my mistake.

**Comment by ideook** [comment]
It was my mistake.
