### ISSUE TITLE
ArgumentNullException in Visual Studio when linking custom WixExtension to Wix4 package

### ISSUE THREAD

**Issue by FireGiantHelp** [firegiant/HeatWaveSupport#49]
### HeatWave Version

1.0.2

### Visual Studio Version

VS 2022 Enterprise x64: 17.7.4

### Repro Steps

See the project in the attached .zip file:

[Wix3to4Examples.zip](https://github.com/firegiant/HeatWaveSupport/files/13651078/Wix3to4Examples.zip)

### Actual Result

1. Referenced WixExtension only overrides the BasePreprocessorExtension class (screenshot 2).
If you comment or delete the task <WixExtension>...</WixExtension> then the error disappears
(see attached project Wix3to4Examples\Wix4Package\Wix4Package.wixproj, line 10-12).
I tried to change the target framework of Wix4Extension project to either netstandard2.0 or net472 but to no avail.

The log file VsProjectFault_449b9831-4c2b-4aee-a7c9-364331790129.failure.txt contains a text like this:

```
14.11.2023 11:26:15
LimitedFunctionality
System.AggregateException: Project system data flow 'DependenciesChangesDataSource: 25218967' closed because of an exception.
Value cannot be null.
Parameter name: evaluationProperties
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
Parameter name: evaluationProperties
   at Microsoft.Requires.NotNull[T](T value, String parameterName)
   at FireGiant.HeatWave.ProjectSystem.SolutionExplorer.Dependencies.DependenciesRuleHandlerBase.IsImplicit(String projectFullPath, IImmutableDictionary`2 evaluationProperties)
   at FireGiant.HeatWave.ProjectSystem.SolutionExplorer.Dependencies.DependenciesRuleHandlerBase.<Handle>g__CreateDependencyModel|10_1(String itemSpec, IProjectRuleSnapshot projectRuleSnapshot, Boolean isResolved, <>c__DisplayClass10_0& A_4)
   at FireGiant.HeatWave.ProjectSystem.SolutionExplorer.Dependencies.DependenciesRuleHandlerBase.<Handle>g__HandleChanges|10_0(Boolean resolved, IProjectChangeDescription projectChange, <>c__DisplayClass10_0& A_3)
   at FireGiant.HeatWave.ProjectSystem.SolutionExplorer.Dependencies.DependenciesRuleHandlerBase.Handle(String projectFullPath, IProjectChangeDescription evaluation, IProjectChangeDescription projectBuild, DependenciesChangesBuilder changesBuilder)
   at FireGiant.HeatWave.ProjectSystem.SolutionExplorer.Dependencies.DependenciesChangesDataSource.ProcessRuleChange(IProjectVersionedValue`1 data)
   at System.Threading.Tasks.Dataflow.TransformBlock`2.ProcessMessage(Func`2 transform, KeyValuePair`2 messageWithId)
   at System.Threading.Tasks.Dataflow.TransformBlock`2.<>c__DisplayClass9_0.<.ctor>b__3(KeyValuePair`2 messageWithId)
   at System.Threading.Tasks.Dataflow.Internal.TargetCore`1.ProcessMessagesLoopCore()
<--- (Inner Exception #0) 
```

![283403855-2ef4e938-5134-4998-8860-927551d9fc6a](https://github.com/firegiant/HeatWaveSupport/assets/118021190/245e8c3d-3f4f-4dd2-8ca8-3a822c39ce7a)

### Expected Result

No exception when building.

**Comment by firegiantco** [comment]
We are not able to reproduce this issue, even using your sample code (thank you for providing that).  Are you still seeing this consistently on the latest version of VS?  Is it intermittent?
